### ISSUE TITLE
Bad label on sending UI : Says 'MEMO', should be 'MIN'

### ISSUE THREAD

**Issue by ChileBob** [nighthawk-apps/nighthawk-wallet-android#11]
**Bug vs expected behavior**
What is the bug? What did you expected to happen instead?

When sending a transaction there's a button to send the max amount, to the left of that there's a button that sends the minimum amount..... but its not labelled correctly (says MEMO)

**Device (please complete the following information):**
 Android: Nokia One

**Comment by nighthawk24** [comment]
Thank you for your suggestion @ChileBob 
The idea behind the "MEMO" naming convention is to make it easier for a user to select the amount required to send an encrypted message only.
Since the target of the app is users who are new to the Zcash ecosystem, it makes sense to mark the buttons per the feature than say min, max which doesn't really convey a meaning as to why send min amount?

The UX can definitely be improved, maybe a separate flow for memo exchanges from the ZEC transfer can help alleviate your concerns.

**Comment by ChileBob** [comment]
That explains it - not a bug :-)
