### ISSUE TITLE
Speed up wallet sync

### ISSUE THREAD

**Issue by the-metalworker** [nighthawk-apps/nighthawk-wallet-android#20]
**Is your feature request related to a problem? Please describe.**
There are two related problems:
- Initial sync when a new wallet is created  
- Subsequent syncs when the wallet is opened

In the first case, it took my wallet 40 minutes for the initial sync. Yes, 40 minutes before I could use the wallet after I first installed it.

In the second case, I open the wallet about once per week and on average it takes 20 minutes before I can use the wallet. 

**Describe the solution you'd like**
I want the wallet to be usable within a few seconds after opening it. I don't know for sure how to make this happen but this is how the wallet should work while still maintaining privacy guarantees.

**Describe alternatives you've considered**
Idea for the initial sync problem: if the wallet is new, there should be no need to sync anything. 
Only sync from that point forward. This would enable the wallet to be usable right away.

Idea for the subsequent sync problem: have the wallet sync in the background from time to time, that way the next way the user opens the wallet it is most likely already almost synced and the user can either use the wallet right away or only have to wait a short amount of time for the wallet to sync before it is usable.

Another complementary idea (not necessarily a replacement for the above) is to allow the user to pair the wallet with their own full node, ideally over Tor for privacy and NAT traversal benefits, so that they can instantaneously get their wallet balance info from their own full node.

**Comment by nighthawk24** [comment]
Thank you for your feedback and solutions @the-metalworker 
We are looking in to moving the synchronizer to a background service.

**Comment by nighthawk24** [comment]
Following up progress around BlazeSync to speed up syncs https://github.com/zcash/lightwalletd/issues/350

**Comment by nighthawk24** [comment]
Incoming https://hackmd.io/@str4d/dagsync-graph-aware-zcash-wallets

**Comment by evanstucker-hates-2fa** [comment]
It's been a while since I opened my wallet. It was using about 8GB of storage. I opened it last night around 7pm and it started downloading again. I let it run all night without opening any other apps - in the morning it was at "Scanning... 8%". It's no using 15GB of storage. I've been running it for another 3 hours this morning and it's now at 11%. This app is not usuable for me in it's current state. Is there anything I can do to speed up downloading or scanning time?

**Comment by evanstucker-hates-2fa** [comment]
As a side note, I can't use other apps on my phone which Nighthawk is doing this or it crashes and has to start over, so I've basically been phoneless since last night because I really want it to finish scanning and I'm hoping it will compact storage or something. 15GB of storage for a wallet isn't going to work for me - I only have 64GB.

**Comment by evanstucker-hates-2fa** [comment]
I really like the idea of having the wallet pointed to my own Zcash node. Anything to make it so that I can actually open it and make a transaction in seconds - even if I haven't opened the wallet in months.

**Comment by hok7z** [comment]
First initialization **very** long. I waited **9 hours** for wallet to download necessary items. After that, there is a scanning it's very long(it may be longer). WTF? I can't use phone when init wallet.

**Comment by nighthawk24** [comment]
A faster syncing method is shipped with v2.
