### ISSUE TITLE
Seed phrase used for Zecwallet Lite not displaying any balance

### ISSUE THREAD

**Issue by bloxster** [nighthawk-apps/nighthawk-wallet-android#6]
**Bug vs expected behavior**
I initiated my NightHawk wallet with the 24 words seed phrase I use also for Zecwallet Lite. No value is displayed, despite I have some funds in Zecwallet Lite. I checked the seed several times and it matches exactly.

**Device **
 - Android Device: Samsung A50 (SM-A505FN)
 - Android Version 10

**Comment by BostonZcash** [comment]
Thanks for the report. Is this Zecwallet Lite for desktop or have you only used the seed for the mobile Zecwallet Lite?

The desktop version generates multiple Z-addresses, while both Zecwallet mobile and Nighthwawk will use only one derived address from the seed, which ought to be the same.

**Comment by bloxster** [comment]
hi,thanks for answering, it is the seed I use for the desktop version.
    Il sabato 15 agosto 2020, 20:46:50 CEST, BostonZcash <notifications@github.com> ha scritto:  
 
 


Thanks for the report. Is this Zecwallet Lite for desktop or have you only used the seed for the mobile Zecwallet Lite?

The desktop version generates multiple Z-addresses, while both Zecwallet mobile and Nighthwawk will use only one derived address from the seed, which ought to be the same.

**Comment by bloxster** [comment]
Update: I tried to use the same seed on a ZecWallet Lite mobile on the same device and it shows the correct balance.

**Comment by BostonZcash** [comment]
Appreciate the update, @bloxster. If you had funds in a Z-address that wasn't the first-derived address from the desktop Zecwallet Lite, that can explain why it's not seen. If that were the case though, I'm not sure why it would be seen if importing into their mobile Zecwallet Lite.

In any case, since compatibility with Zecwallet seeds isn't an intended feature of ours at the moment I'll close this issue, though we'll be looking at interoperability with other Zcash services and wallets. Please reach out with any new feedback!
